# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 我的博客
email: scenery18032@163.com
description:  这是我的gitpage网站
baseurl: "/scenery18032.github.io" # the subpath of your site, e.g. /blog
url: "http://scenery18032.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  scenery18032
# Build settings
markdown: 
